config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :products do
      resources :reviews
    end
  end
  devise_for :users
  get 'users/show'
  root 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates :name, presence: true, uniqueness: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews

  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :price

  validates_format_of :price, :with => /\A\d+\.*\d{0,2}\z/ 

  def average_rating
    sum = 0.0
    self.reviews.each do |r|
      sum += r.rating
    end
    avg = sum / self.reviews.count
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  
  validates_presence_of :content
  validates_presence_of :user_id
  validates_presence_of :rating

  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :firstname
  validates_presence_of :lastname

  has_many :reviews
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception

	protected

  	def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :firstname
      devise_parameter_sanitizer.for(:sign_up) << :lastname
      devise_parameter_sanitizer.for(:account_update) << :firstname
      devise_parameter_sanitizer.for(:account_update) << :lastname
    end

    def authenticate_admin
  		if !current_user || !current_user.admin?
  			redirect_to new_user_session_path, :notice => "You are not permitted to perform this operation."
  		end
  	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  
  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.category = Category.new(category_params)

    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :check_owner, only: [:edit, :update]
  expose(:category)
  expose(:products)
  expose(:product)
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)

  def index
    self.products = category.products
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    prod = Product.new(product_params)
    prod.user = current_user
    self.product = prod

    if product.save
      category.products << product
      redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if self.product.update(product_params)
      redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /products/1
  def destroy
    product.destroy
    redirect_to category_url(product.category), notice: 'Product was successfully destroyed.'
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id)
  end

  def check_owner
    if product.user != current_user
      redirect_to category_product_url(category, product), flash[:error] = 'Permission denied' 
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  expose(:review)
  expose(:product)

  def edit
  end

  def create
    rev = Review.new(review_params)
    rev.user = current_user
    self.review = rev

    if review.save
      product.reviews << review
      redirect_to category_product_url(product.category, product), notice: 'Review was successfully created.'
    else
      redirect_to category_product_url(product.category, product), flash[:error] = 'Review could not be created.' 
    end
  end

  def destroy
    review.destroy
    redirect_to category_product_url(product.category, product), notice: 'Review was successfully destroyed.'
  end

  private
    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  expose_decorated(:user) { current_user }
  expose_decorated(:reviews, ancestor: :user)

  def show
  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.haml
= form_for category do |f|
  - if category.errors.any?
    #error_explanation.alert.alert-danger
      %p= "#{pluralize(category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-primary glyphicon glyphicon-ok'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', category, class: 'btn btn-default glyphicon glyphicon-th'
= link_to 'Back', categories_path, class: 'btn btn-default glyphicon glyphicon-chevron-left'

app/views/categories/index.html.haml
- if current_user and current_user.admin?
  = link_to 'New Category', new_category_path, class: 'btn btn-success'
%h1 Categories:
- if categories.count == 0
  %p
    %i No categories yet.
- else
  %ul.list-group
    - categories.each do |category|
      .row
        .col-md-8
          %b= link_to category.name, category, class: 'list-group-item'
        .col-md-4  
          - if current_user and current_user.admin?
            %span.badge
              = link_to 'Edit', edit_category_path(category), class: 'btn btn-warning glyphicon glyphicon-pencil'
              = link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger glyphicon glyphicon-remove'

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path, class: 'btn btn-primary glyphicon glyphicon-chevron-left'

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Category:
  = category.name

%br

- if user_signed_in?
  = link_to 'Add new product', new_category_product_path(category), class: 'btn btn-success'

  %h2
    %b Products:

= render partial: 'products/list', object: category.products

%br
- if current_user and current_user.admin?
  = link_to 'Edit category', edit_category_path(category), class: 'btn btn-warning'
= link_to 'Back', categories_path, class: 'btn btn-default glyphicon glyphicon-chevron-left glyphicon glyphicon-pencil'

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          %a.navbar-brand{ href: root_path } #{AppConfig.workshops_name}
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li
              %p.navbar-text= 'Signed in as ' + current_user.firstname + ' ' + current_user.lastname
            %li= link_to 'Profile', users_show_path
            %li= link_to 'Log out', destroy_user_session_path, :method => :delete
          - else
            %li= link_to 'Log in', new_user_session_path
            %li= link_to 'Register', new_user_registration_path

    .container-fluid
      .row
        .col-lg-12
          - if flash[:notice]
            %div.alert.alert-info= flash[:notice]
          - if flash[:alert]
            %div.alert.alert-danger= flash[:alert]
          - if flash[:error]
            %div.alert.alert-danger= flash[:error] 
          = yield

app/views/products/_form.html.haml
= form_for [category, product] do |f|
  - if product.errors.any?
    #error_explanation.alert.alert-danger
      %p= "#{pluralize(product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - product.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-primary glyphicon glyphicon-ok'

app/views/products/_list.html.haml
- if list.count == 0
  %p
    %i There are no products in this category.

- else

  %table.table
    %thead
      %tr
        %th Title
        %th Description
        %th Price
        %th
        %th
        %th
    %tbody
      - list.each do |product|
        %tr
          %td
            = link_to product.title, category_product_path(product.category, product)
          %td= product.description
          %td= product.price
          %td= link_to 'Show', category_product_path(product.category, product), class: 'btn btn-primary glyphicon glyphicon-th' 
          - if product.user == current_user
            %td= link_to 'Edit', edit_category_product_path(product.category, product), class: 'btn btn-warning glyphicon glyphicon-pencil'
            %td= link_to 'Delete', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger glyphicon glyphicon-remove'

%br

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', category_product_path(category, product), class: 'btn btn-default glyphicon glyphicon-th'
= link_to 'Back', category_path(category), class: 'btn btn-default glyphicon glyphicon-chevron-left'

app/views/products/index.html.haml
%h1
  = 'Products of '
  %b
    = link_to category.name, category_path(category)
  = ' category:'

- if user_signed_in?
  = link_to 'Add new product', new_category_product_path(category), class: 'btn btn-success'

= render partial: 'products/list', object: category.products

%br

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', category_products_path, class: 'btn btn-default glyphicon glyphicon-chevron-left'

app/views/products/show.html.haml
%h2
  = "Product title: "
  %b= product.title

%p
  %b Category:
  = link_to product.category.name, category_path(product.category)
%p
  %b Description:
  = product.description
%p
  %b Price:
  = product.price

%br

- if current_user == product.user
  = link_to 'Edit product', edit_category_product_path(category.id, product.id),  class: 'btn btn-warning glyphicon glyphicon-chevron-pencil'
= link_to 'Back', category_products_path, class: 'btn btn-default glyphicon glyphicon-chevron-left'

%br

- if user_signed_in?
  %br
  %h4 Add review:
  = render 'reviews/form'

%h3 Reviews

- if product.reviews.count == 0
  %p
    %i No reviews yet.
- else
  %ul.list-group

= render reviews
%br

app/views/reviews/_form.html.haml
= simple_form_for [category, product, review] do |f|
  - if review.errors.any?
    #error_explanation
      %h2= "#{pluralize(review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - review.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'
  .form-group
    = f.input :rating, collection: 1..5, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default glyphicon glyphicon-chevron-ok'

app/views/reviews/_review.html.haml
%li.list-group-item
%p= review.content
%p
  %b= review.rating
  %em= review.author
  %br
  %small= review.created_at.strftime("%d-%m-%y")

app/views/users/show.html.haml
%h2 
  = current_user.firstname + ' ' + current_user.lastname
  
%p
%b First name:
= current_user.firstname

%p
%b Last name:
= current_user.lastname

%p
%b Email address:
%a{href: 'mailto:' + current_user.email}
  = current_user.email

%br
%br

%h4 Your latest reviews:
.row
  .col-md-6
    - if reviews.count == 0
      %p
        %i No reviews yet.
    - else
      %ul.list-group
      = render reviews.sort_by{|t| - t.created_at.to_i}.first(5)

= link_to 'Edit profile', edit_user_registration_path, class: 'btn btn-warning glyphicon glyphicon-chevron-pencil'